services:
  nodejs_container:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
  mongodb_container:
    # This image automatically creates a replica set required for transactions, as prisma needs.
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 10
    ports:
      - 27017:27017
